#!/bin/sh
#
#
# To enable this hook, rename this file to "pre-commit".

#!/usr/bin/env bash
LC_ALL=C
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

LOCAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
VALID_BRANCH_REGEX="^(feature|bugfix|improvement|library|release|hotfix)\/[a-z0-9._-]+$"
message="There is something wrong with your branch name ${LOCAL_BRANCH}. Branch names in this project must adhere to this contract: ${VALID_BRANCH_REGEX}. You should rename your branch to a valid name and try again."

# check branch naming
echo -e "${YELLOW}Running pre-commit hook, checking branch name${NC}"
if [[ ! $LOCAL_BRANCH =~ $VALID_BRANCH_REGEX ]]
then
    echo -e "${RED}$message${NC}"
    exit 1
fi

# other check...

exit 0
